from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from homeassistant.core import HomeAssistant
from homeassistant.helpers import entity_registry as er


@dataclass(frozen=True, slots=True)
class CezHdoSource:
    """One detected ČEZ HDO source set."""

    source_id: str
    name: str
    schedule_entity_id: str
    low_tariff_entity_id: str | None = None
    current_price_entity_id: str | None = None
    data_valid_entity_id: str | None = None
    signal: str | None = None


async def async_discover_cez_hdo_sources(hass: HomeAssistant) -> list[CezHdoSource]:
    """Discover ČEZ HDO devices without relying on user-specific entity IDs.

    A structured schedule sensor is the anchor. Related entities are matched by
    device/config-entry registry metadata and by the common suffix generated by
    the source integration. This supports arbitrary user names and HDO signals.
    """

    registry = er.async_get(hass)
    candidates: list[CezHdoSource] = []

    for state in hass.states.async_all("sensor"):
        if not _looks_like_schedule(state.attributes.get("schedule")):
            continue

        entry = registry.async_get(state.entity_id)
        signal = _as_text(state.attributes.get("signal"))
        group = _related_entity_ids(registry, entry)
        suffix = _entity_suffix(state.entity_id, "schedule")

        low_tariff = _find_related(
            hass,
            group,
            domain="binary_sensor",
            required_tokens=("lowtariffactive", "low_tariff_active"),
            preferred_suffix=suffix,
            signal=signal,
        )
        current_price = _find_related(
            hass,
            group,
            domain="sensor",
            required_tokens=("currentprice", "current_price"),
            preferred_suffix=suffix,
            signal=signal,
        )
        data_valid = _find_related(
            hass,
            group,
            domain="binary_sensor",
            required_tokens=("data_valid", "datavalid"),
            preferred_suffix=suffix,
            signal=signal,
        )

        if entry is not None and entry.device_id:
            source_id = entry.device_id
        elif entry is not None and entry.config_entry_id:
            source_id = f"{entry.config_entry_id}:{signal or suffix or state.entity_id}"
        else:
            source_id = signal or state.entity_id

        name = state.attributes.get("friendly_name") or signal or state.entity_id
        candidates.append(
            CezHdoSource(
                source_id=source_id,
                name=str(name),
                schedule_entity_id=state.entity_id,
                low_tariff_entity_id=low_tariff,
                current_price_entity_id=current_price,
                data_valid_entity_id=data_valid,
                signal=signal,
            )
        )

    return _deduplicate(candidates)


def _looks_like_schedule(value: Any) -> bool:
    if not isinstance(value, list) or not value:
        return False
    sample = value[0]
    return isinstance(sample, dict) and {"start", "end", "tariff"}.issubset(sample)


def _related_entity_ids(
    registry: er.EntityRegistry, anchor: er.RegistryEntry | None
) -> list[str]:
    if anchor is None:
        return []

    result: list[str] = []
    for entry in registry.entities.values():
        same_device = bool(anchor.device_id and entry.device_id == anchor.device_id)
        same_config = bool(
            not anchor.device_id
            and anchor.config_entry_id
            and entry.config_entry_id == anchor.config_entry_id
        )
        if same_device or same_config:
            result.append(entry.entity_id)
    return result


def _find_related(
    hass: HomeAssistant,
    entity_ids: list[str],
    *,
    domain: str,
    required_tokens: tuple[str, ...],
    preferred_suffix: str | None,
    signal: str | None,
) -> str | None:
    matches = [
        entity_id
        for entity_id in entity_ids
        if entity_id.startswith(f"{domain}.")
        and any(token in entity_id.lower() for token in required_tokens)
    ]
    if preferred_suffix:
        exact = next(
            (entity_id for entity_id in matches if entity_id.endswith(preferred_suffix)),
            None,
        )
        if exact:
            return exact
    if len(matches) == 1:
        return matches[0]

    for state in hass.states.async_all(domain):
        lowered = state.entity_id.lower()
        if not any(token in lowered for token in required_tokens):
            continue
        if preferred_suffix and state.entity_id.endswith(preferred_suffix):
            return state.entity_id
        if signal is not None and state.attributes.get("signal") == signal:
            return state.entity_id
    return None


def _entity_suffix(entity_id: str, marker: str) -> str | None:
    object_id = entity_id.split(".", 1)[-1]
    token = f"_{marker}_"
    if token not in object_id:
        return None
    return object_id.split(token, 1)[1]


def _deduplicate(sources: list[CezHdoSource]) -> list[CezHdoSource]:
    result: dict[str, CezHdoSource] = {}
    for source in sources:
        result[source.source_id] = source
    return sorted(result.values(), key=lambda item: item.name.casefold())


def _as_text(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    return text or None
